### ISSUE TITLE
Version 0.6.x Documentation Improvements

### ISSUE THREAD

**Issue by hiltontj** [hiltontj/serde_json_path#41]
The purpose of this issue is to track some necessary improvements/fixes in the [crate documentation](https://docs.rs/serde_json_path/latest/serde_json_path/).

- [x] No explanation in the [Recursive Descent section
](https://docs.rs/serde_json_path/latest/serde_json_path/#recursive-descent-) (#53)
- [x] The second example in [Filter Expressions](https://docs.rs/serde_json_path/latest/serde_json_path/#filter-expressions-) seems like a poor use of the `$` token in a filter expression (#54)
- [x] The [slice selector section](https://docs.rs/serde_json_path/latest/serde_json_path/index.html#slice-selectors-startendstep) could use a separate example for reverse indices. (#55)
- [x] The [filter selectors section](https://docs.rs/serde_json_path/latest/serde_json_path/index.html#filter-expressions-) should be generally re-worded. The focus on existence and comparison is perhaps a bit outdated, and it may be useful to mention functions earlier on. (#56)
- [x] #57
- [x] The note about more lenient accessors could be moved to the end of [the section](https://docs.rs/serde_json_path/latest/serde_json_path/#querying-for-single-nodes). (#56)
- [x] The description in serde_json_path crate Cargo.toml should use the word "query" instead of "parse" and omit the trailing "queries" (#52)
- [x] #58
- [x] Code examples for methods in `NodeList` that do not have them, e.g., `first`, `last`, `get` (#56)

**Comment by hiltontj** [comment]
Two items in this issue have been converted to separate issues (#57 and #58). Otherwise, all documentation updates have been made, so this can be closed.
